services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.12
    container_name: sentinel-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: sentinel
      CLICKHOUSE_USER: sentinel
      CLICKHOUSE_PASSWORD: sentinel_pass
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./sql/init:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse-data:
